### ISSUE TITLE
Conversation agent language selection

### ISSUE THREAD

**Issue by noxhirsch** [siemon-geeroms/yarvis#3]
Since the default Home Assistant parser gets triggered without language info, it assumes English input and doesn't try to parse my german custom sentences. When I replace `None` with `"de"` everything is working.
https://github.com/siemon-geeroms/yarvis/blob/6f53151ac8d747216fb924c566b274c3f4f9f7fc/custom_components/yarvis/__init__.py#L67

I think the best solution would be, to have a language selector like with the default parser (maybe in the options dialog):
![image](https://github.com/siemon-geeroms/yarvis/assets/30938717/4f28250d-c9a2-4ec9-8b7c-bbabd4403476)

**Comment by siemon-geeroms** [comment]
hi, I had the same problem and can you check if the language is set to german in the general settings?

![image](https://github.com/siemon-geeroms/yarvis/assets/18004207/f2733f2c-7bf7-4523-b2ff-74b4b28d4477)

**Comment by noxhirsch** [comment]
Hi, thanks for the tip! That makes sense of course - I had totally forgotten that there is also a language selection for the server and had only tested changing the language to German in the user settings. Now it works wonderfully 👍
